package entity

import "time"

type Card struct {
	ID          int64 // id в бд
	Title       string
	Category    string
	Description string
}

type AutoGenerated struct {
	Cards []struct {
		NmID        int    `json:"nmID"`
		ImtID       int    `json:"imtID"`
		NmUUID      string `json:"nmUUID"`
		SubjectID   int    `json:"subjectID"`
		SubjectName string `json:"subjectName"`
		VendorCode  string `json:"vendorCode"`
		Brand       string `json:"brand"`
		Title       string `json:"title"`
		Description string `json:"description"`
		Dimensions  struct {
			Length int `json:"length"`
			Width  int `json:"width"`
			Height int `json:"height"`
		} `json:"dimensions"`
		Characteristics []Characteristic `json:"characteristics"`
		Sizes           []Size           `json:"sizes"`
		CreatedAt       time.Time        `json:"createdAt"`
		UpdatedAt       time.Time        `json:"updatedAt"`
	} `json:"cards"`
	Cursor struct {
		UpdatedAt time.Time `json:"updatedAt"`
		NmID      int       `json:"nmID"`
		Total     int       `json:"total"`
	} `json:"cursor"`
}

type Characteristic struct {
	ID    int      `json:"id"`
	Name  string   `json:"name"`
	Value []string `json:"value"`
}

type Size struct {
	ChrtID   int      `json:"chrtID"`
	TechSize string   `json:"techSize"`
	Skus     []string `json:"skus"`
}

type Brand struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
