global:
  scrape_interval:     2s # Как часто собирать метрики
  evaluation_interval: 2s # Как часто вычислять правила агрегации и алертинга

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: "app"
    static_configs:
      - targets: [ "data-receiver:8080" ]
  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx] # Используем модуль из blackbox.yml
    static_configs:
      - targets: ["data-receiver:8080"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115 # Указываем Blackbox Exporter 
  - job_name: "node-exporter"
    static_configs:
      - targets: [ "node-exporter:9100" ]
