global:
  scrape_interval:     2s # Как часто собирать метрики
  evaluation_interval: 2s # Как часто вычислять правила агрегации и алертинга

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: "app"
    static_configs:
      - targets: [ "data-receiver:8080" ]
