// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: receiver-service.proto

package package_receiver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PackageReceiverClient is the client API for PackageReceiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PackageReceiverClient interface {
	CheckHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetCard(ctx context.Context, in *GetCardRequest, opts ...grpc.CallOption) (*GetCardResponse, error)
}

type packageReceiverClient struct {
	cc grpc.ClientConnInterface
}

func NewPackageReceiverClient(cc grpc.ClientConnInterface) PackageReceiverClient {
	return &packageReceiverClient{cc}
}

func (c *packageReceiverClient) CheckHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/package_receiver.PackageReceiver/CheckHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packageReceiverClient) GetCard(ctx context.Context, in *GetCardRequest, opts ...grpc.CallOption) (*GetCardResponse, error) {
	out := new(GetCardResponse)
	err := c.cc.Invoke(ctx, "/package_receiver.PackageReceiver/GetCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PackageReceiverServer is the server API for PackageReceiver service.
// All implementations must embed UnimplementedPackageReceiverServer
// for forward compatibility
type PackageReceiverServer interface {
	CheckHealth(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	GetCard(context.Context, *GetCardRequest) (*GetCardResponse, error)
	mustEmbedUnimplementedPackageReceiverServer()
}

// UnimplementedPackageReceiverServer must be embedded to have forward compatible implementations.
type UnimplementedPackageReceiverServer struct {
}

func (UnimplementedPackageReceiverServer) CheckHealth(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedPackageReceiverServer) GetCard(context.Context, *GetCardRequest) (*GetCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCard not implemented")
}
func (UnimplementedPackageReceiverServer) mustEmbedUnimplementedPackageReceiverServer() {}

// UnsafePackageReceiverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PackageReceiverServer will
// result in compilation errors.
type UnsafePackageReceiverServer interface {
	mustEmbedUnimplementedPackageReceiverServer()
}

func RegisterPackageReceiverServer(s grpc.ServiceRegistrar, srv PackageReceiverServer) {
	s.RegisterService(&PackageReceiver_ServiceDesc, srv)
}

func _PackageReceiver_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageReceiverServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/package_receiver.PackageReceiver/CheckHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageReceiverServer).CheckHealth(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PackageReceiver_GetCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageReceiverServer).GetCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/package_receiver.PackageReceiver/GetCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageReceiverServer).GetCard(ctx, req.(*GetCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PackageReceiver_ServiceDesc is the grpc.ServiceDesc for PackageReceiver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PackageReceiver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "package_receiver.PackageReceiver",
	HandlerType: (*PackageReceiverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckHealth",
			Handler:    _PackageReceiver_CheckHealth_Handler,
		},
		{
			MethodName: "GetCard",
			Handler:    _PackageReceiver_GetCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "receiver-service.proto",
}
