// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.2
// source: receiver-service.proto

package package_receiver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CardReceiverClient is the client API for CardReceiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CardReceiverClient interface {
	CheckHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetCard(ctx context.Context, in *GetCardRequest, opts ...grpc.CallOption) (*GetCardResponse, error)
}

type cardReceiverClient struct {
	cc grpc.ClientConnInterface
}

func NewCardReceiverClient(cc grpc.ClientConnInterface) CardReceiverClient {
	return &cardReceiverClient{cc}
}

func (c *cardReceiverClient) CheckHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/package_receiver.CardReceiver/CheckHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardReceiverClient) GetCard(ctx context.Context, in *GetCardRequest, opts ...grpc.CallOption) (*GetCardResponse, error) {
	out := new(GetCardResponse)
	err := c.cc.Invoke(ctx, "/package_receiver.CardReceiver/GetCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardReceiverServer is the server API for CardReceiver service.
// All implementations must embed UnimplementedCardReceiverServer
// for forward compatibility
type CardReceiverServer interface {
	CheckHealth(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	GetCard(context.Context, *GetCardRequest) (*GetCardResponse, error)
	mustEmbedUnimplementedCardReceiverServer()
}

// UnimplementedCardReceiverServer must be embedded to have forward compatible implementations.
type UnimplementedCardReceiverServer struct {
}

func (UnimplementedCardReceiverServer) CheckHealth(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedCardReceiverServer) GetCard(context.Context, *GetCardRequest) (*GetCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCard not implemented")
}
func (UnimplementedCardReceiverServer) mustEmbedUnimplementedCardReceiverServer() {}

// UnsafeCardReceiverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CardReceiverServer will
// result in compilation errors.
type UnsafeCardReceiverServer interface {
	mustEmbedUnimplementedCardReceiverServer()
}

func RegisterCardReceiverServer(s grpc.ServiceRegistrar, srv CardReceiverServer) {
	s.RegisterService(&CardReceiver_ServiceDesc, srv)
}

func _CardReceiver_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardReceiverServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/package_receiver.CardReceiver/CheckHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardReceiverServer).CheckHealth(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardReceiver_GetCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardReceiverServer).GetCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/package_receiver.CardReceiver/GetCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardReceiverServer).GetCard(ctx, req.(*GetCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CardReceiver_ServiceDesc is the grpc.ServiceDesc for CardReceiver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CardReceiver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "package_receiver.CardReceiver",
	HandlerType: (*CardReceiverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckHealth",
			Handler:    _CardReceiver_CheckHealth_Handler,
		},
		{
			MethodName: "GetCard",
			Handler:    _CardReceiver_GetCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "receiver-service.proto",
}
