// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.2
// source: receiver-service.proto

package package_receiver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CardReceiver_CheckHealth_FullMethodName      = "/package_receiver.CardReceiver/CheckHealth"
	CardReceiver_ReceiveCard_FullMethodName      = "/package_receiver.CardReceiver/ReceiveCard"
	CardReceiver_ReceiveWarehouse_FullMethodName = "/package_receiver.CardReceiver/ReceiveWarehouse"
	CardReceiver_ReceiveStock_FullMethodName     = "/package_receiver.CardReceiver/ReceiveStock"
	CardReceiver_OfferFeed_FullMethodName        = "/package_receiver.CardReceiver/OfferFeed"
)

// CardReceiverClient is the client API for CardReceiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CardReceiverClient interface {
	CheckHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReceiveCard(ctx context.Context, in *ReceiveCardRequest, opts ...grpc.CallOption) (*ReceiveCardResponse, error)
	ReceiveWarehouse(ctx context.Context, in *ReceiveWarehouseRequest, opts ...grpc.CallOption) (*ReceiveWarehouseResponse, error)
	ReceiveStock(ctx context.Context, in *ReceiveStockRequest, opts ...grpc.CallOption) (*ReceiveStockResponse, error)
	OfferFeed(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OfferFeedResponse, error)
}

type cardReceiverClient struct {
	cc grpc.ClientConnInterface
}

func NewCardReceiverClient(cc grpc.ClientConnInterface) CardReceiverClient {
	return &cardReceiverClient{cc}
}

func (c *cardReceiverClient) CheckHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CardReceiver_CheckHealth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardReceiverClient) ReceiveCard(ctx context.Context, in *ReceiveCardRequest, opts ...grpc.CallOption) (*ReceiveCardResponse, error) {
	out := new(ReceiveCardResponse)
	err := c.cc.Invoke(ctx, CardReceiver_ReceiveCard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardReceiverClient) ReceiveWarehouse(ctx context.Context, in *ReceiveWarehouseRequest, opts ...grpc.CallOption) (*ReceiveWarehouseResponse, error) {
	out := new(ReceiveWarehouseResponse)
	err := c.cc.Invoke(ctx, CardReceiver_ReceiveWarehouse_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardReceiverClient) ReceiveStock(ctx context.Context, in *ReceiveStockRequest, opts ...grpc.CallOption) (*ReceiveStockResponse, error) {
	out := new(ReceiveStockResponse)
	err := c.cc.Invoke(ctx, CardReceiver_ReceiveStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardReceiverClient) OfferFeed(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OfferFeedResponse, error) {
	out := new(OfferFeedResponse)
	err := c.cc.Invoke(ctx, CardReceiver_OfferFeed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardReceiverServer is the server API for CardReceiver service.
// All implementations must embed UnimplementedCardReceiverServer
// for forward compatibility
type CardReceiverServer interface {
	CheckHealth(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	ReceiveCard(context.Context, *ReceiveCardRequest) (*ReceiveCardResponse, error)
	ReceiveWarehouse(context.Context, *ReceiveWarehouseRequest) (*ReceiveWarehouseResponse, error)
	ReceiveStock(context.Context, *ReceiveStockRequest) (*ReceiveStockResponse, error)
	OfferFeed(context.Context, *emptypb.Empty) (*OfferFeedResponse, error)
	mustEmbedUnimplementedCardReceiverServer()
}

// UnimplementedCardReceiverServer must be embedded to have forward compatible implementations.
type UnimplementedCardReceiverServer struct {
}

func (UnimplementedCardReceiverServer) CheckHealth(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedCardReceiverServer) ReceiveCard(context.Context, *ReceiveCardRequest) (*ReceiveCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveCard not implemented")
}
func (UnimplementedCardReceiverServer) ReceiveWarehouse(context.Context, *ReceiveWarehouseRequest) (*ReceiveWarehouseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveWarehouse not implemented")
}
func (UnimplementedCardReceiverServer) ReceiveStock(context.Context, *ReceiveStockRequest) (*ReceiveStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveStock not implemented")
}
func (UnimplementedCardReceiverServer) OfferFeed(context.Context, *emptypb.Empty) (*OfferFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OfferFeed not implemented")
}
func (UnimplementedCardReceiverServer) mustEmbedUnimplementedCardReceiverServer() {}

// UnsafeCardReceiverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CardReceiverServer will
// result in compilation errors.
type UnsafeCardReceiverServer interface {
	mustEmbedUnimplementedCardReceiverServer()
}

func RegisterCardReceiverServer(s grpc.ServiceRegistrar, srv CardReceiverServer) {
	s.RegisterService(&CardReceiver_ServiceDesc, srv)
}

func _CardReceiver_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardReceiverServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardReceiver_CheckHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardReceiverServer).CheckHealth(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardReceiver_ReceiveCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardReceiverServer).ReceiveCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardReceiver_ReceiveCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardReceiverServer).ReceiveCard(ctx, req.(*ReceiveCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardReceiver_ReceiveWarehouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveWarehouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardReceiverServer).ReceiveWarehouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardReceiver_ReceiveWarehouse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardReceiverServer).ReceiveWarehouse(ctx, req.(*ReceiveWarehouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardReceiver_ReceiveStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardReceiverServer).ReceiveStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardReceiver_ReceiveStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardReceiverServer).ReceiveStock(ctx, req.(*ReceiveStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardReceiver_OfferFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardReceiverServer).OfferFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardReceiver_OfferFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardReceiverServer).OfferFeed(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CardReceiver_ServiceDesc is the grpc.ServiceDesc for CardReceiver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CardReceiver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "package_receiver.CardReceiver",
	HandlerType: (*CardReceiverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckHealth",
			Handler:    _CardReceiver_CheckHealth_Handler,
		},
		{
			MethodName: "ReceiveCard",
			Handler:    _CardReceiver_ReceiveCard_Handler,
		},
		{
			MethodName: "ReceiveWarehouse",
			Handler:    _CardReceiver_ReceiveWarehouse_Handler,
		},
		{
			MethodName: "ReceiveStock",
			Handler:    _CardReceiver_ReceiveStock_Handler,
		},
		{
			MethodName: "OfferFeed",
			Handler:    _CardReceiver_OfferFeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "receiver-service.proto",
}
